/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /Library/MobileSubstrate/DynamicLibraries/ScrollingBoard.dylib
 */


@interface PMDockPlugins : NSObject 
+(PMDockPlugins *)sharedInstance;
-(NSString *)pluginForPage:(int)page;
-(NSString *)pluginOnCurrentPage;
-(void)scrollToPluginNamed:(NSString *)named;
-(void)scrollToPluginNamed:(NSString *)named animated:(BOOL)animated;
@end

