/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /Library/MobileSubstrate/DynamicLibraries/ScrollingBoard.dylib
 */

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface PMDockPlugins : NSObject {
	NSMutableArray* cachedPlugins;
	NSMutableArray* loadedPlugins;
}
@property(retain) NSMutableArray* loadedPlugins;
@property(retain) NSMutableArray* cachedPlugins;
+(id)sharedInstance;
+(id)pluginNamesInDictionary:(id)dictionary;
-(id)init;
-(BOOL)insertPluginNamed:(id)named withView:(id)view force:(BOOL)force;
-(BOOL)insertPluginFromBundle:(id)bundle force:(BOOL)force;
-(BOOL)insertPluginNamed:(id)named withView:(id)view andBundle:(id)bundle force:(BOOL)force;
-(BOOL)insertPluginNamed:(id)named withView:(id)view;
-(id)pluginNamed:(id)named;
-(id)enabledPlugins;
-(BOOL)addAllPluginViewsToDockScrollView;
-(BOOL)removeAllPluginViewsFromDockScrollView;
-(BOOL)removePluginNamed:(id)named;
@end

