/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /Library/MobileSubstrate/DynamicLibraries/ScrollingBoard.dylib
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, SBIconScrollView;

@interface PMSBPlugins : NSObject {
	SBIconScrollView* iconScrollView;
	NSMutableArray* keyboardPluginsArr;
	NSMutableArray* copiedPlugins;
	NSMutableArray* cachedPlugins;
	NSMutableArray* loadedPlugins;
}
@property(retain, nonatomic) NSMutableArray* loadedPlugins;
@property(retain, nonatomic) NSMutableArray* cachedPlugins;
@property(retain, nonatomic) NSMutableArray* copiedPlugins;
@property(retain, nonatomic) NSMutableArray* keyboardPluginsArr;
@property(retain, nonatomic) SBIconScrollView* iconScrollView;
+(id)sharedInstance;
-(id)init;
-(id)pluginForPage:(int)page;
-(id)pluginNamed:(id)named;
-(int)pageWithPluginNamed:(id)pluginNamed;
-(void)scrollToPluginNamed:(id)pluginNamed;
-(void)removeAllPluginViewsFromSpringBoardScrollView;
-(void)addAllPluginViewsToSpringBoardScrollView;
-(BOOL)removePluginNamed:(id)named;
-(BOOL)insertPluginFromBundle:(id)bundle force:(BOOL)force;
-(BOOL)insertPluginNamed:(id)named withView:(id)view requiresKeyboard:(BOOL)keyboard force:(BOOL)force;
-(BOOL)insertPluginNamed:(id)named withView:(id)view andBundle:(id)bundle requiresKeyboard:(BOOL)keyboard force:(BOOL)force;
-(BOOL)insertPluginNamed:(id)named withView:(id)view force:(BOOL)force;
@end

