/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /Library/MobileSubstrate/DynamicLibraries/ScrollingBoard.dylib
 */

#import <Foundation/NSObject.h>


@interface PMSBPlugins : NSObject 
+(PMSBPlugins *)sharedInstance;
-(NSString *)pluginOnCurrentPage;
-(NSString *)pluginNameOnPage:(int)page;
-(void)scrollToPluginNamed:(NSString *)pluginName;
-(void)scrollToPluginNamed:(NSString *)pluginName animated:(BOOL)animated;
@end

